name: Gold Rate Notifier

'on':
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send-gold-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Gold Notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          METALS_API_KEY: ${{ secrets.METALS_API_KEY }}
        run: go run ./cmd/main.go
